### ISSUE TITLE
Created glyph uses different case than the entered glyph name

### ISSUE THREAD

**Issue by ollimeier** [googlefonts/fontra#1093]
I wanted to create a new glyph called /h.ss01. I double clicked on the new glyph and fontra created a new glyph called /H.ss01. So, it changed it to uppercase. 
<img width="1596" alt="Screenshot 2024-02-16 at 09 57 29" src="https://github.com/googlefonts/fontra/assets/21055547/75015442-927e-4244-a74b-bcb15324502c">
<img width="1596" alt="Screenshot 2024-02-16 at 09 58 01" src="https://github.com/googlefonts/fontra/assets/21055547/3e8d3ab8-846a-4cac-ad9a-c105af3dbbad">

**Comment by justvanrossum** [comment]
This is a side effect of https://github.com/googlefonts/fontra/pull/885, which is a useful feature, but it is at least confusing in this case. In short, what is happening is that for a non-existing glyphname `/h.alt`, it is checked whether `/h` exists, and if it doesn't (as is the case here), it interprets `h` as a character, which is U+0068, and then it tries to find a glyph for that character. In this font `/H` is used both for U+0068 and U+0048 (cap H), so it finds the glyph '/H`...

The use case for this is that users can do `/㐱.alt` as a short cut for `/uni3431.alt`, or `/Å.alt` as a short cut for `/Aring.alt`.

For this particular font, substituting `H` for `h`, that wouldn't even be a bug, since it's caps-only, and `/h.ss01` wouldn't make sense.

But this is still confusing, and Fontra shouldn't make that decision for the user. I think this can be fixed by disabling the behavior in the case where the glyph name is actually the same as the character. Perhaps we can just hard code A-Z and a-z, because as far as I can see those are the only cases this can happen.

**Comment by ollimeier** [comment]
There are other issues as well. /.notdef get changed to /.notde and /.null -> /.nul 
when a character starts with a dot eg like for /.notdef the last character is missing.
<img width="1822" alt="Screenshot 2024-02-19 at 14 10 52" src="https://github.com/googlefonts/fontra/assets/21055547/f09af301-7597-4390-86f9-d1e082c2ae40">
<img width="1822" alt="Screenshot 2024-02-19 at 14 11 13" src="https://github.com/googlefonts/fontra/assets/21055547/4d4e5982-af80-4c9e-b728-29d3c6d6209d">

**Comment by justvanrossum** [comment]
I see there's also a bug in `glyphnames.getUnicodeFromGlyphName()`: it raises KeyError on `.notdef`:

```
Traceback (most recent call last):
  File "/Users/just/code/git/BlackFoundry/fontra/src/fontra/core/server.py", line 226, in webAPIHandler
    returnValue = function(**kwargs)
                  ^^^^^^^^^^^^^^^^^^
  File "/Users/just/code/git/BlackFoundry/fontra/src/fontra/core/serverutils.py", line 19, in getUnicodeFromGlyphName
    return glyphnames.getUnicodeFromGlyphName(glyphName)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/just/code/git/BlackFoundry/fontra/src/fontra/core/glyphnames.py", line 33, in getUnicodeFromGlyphName
    codePoint = int(info["unicode"], 16)
                    ~~~~^^^^^^^^^^^
KeyError: 'unicode'
```

**Comment by ollimeier** [comment]
Jepp, I found that already and I am on the way to fix it. I just have trouble with flake8 :(
