### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by Aaron-212** [googlefonts/fontra#1340]
Will Fontra consider supporting languages other than English?
Also, I just started testing localization support myself.
<https://github.com/Aaron-212/fontra/tree/localization-support>

**Comment by justvanrossum** [comment]
We will consider for sure! I'd like to study your proposal more thoroughly, thanks for sharing.

I have zero experience with localizing web apps, and I'm curious what the best practices are.

@fabiocaccamo, can you have a look at the changes in the above fork, and can you say something about best practices surrounding localizations?

For translatations, we would have nearby experts for:
- Chinese
- Japanese
- Korean
- French
- German
- Dutch

**Comment by fabiocaccamo** [comment]
@justvanrossum the localization approach started by @Aaron-212, even if very basic, is the right one, however there are some important requirements: 

- [ ] adding support to [plural forms](https://phrase.com/blog/posts/pluralization/) *(this is not trivial, it would be better to use some existing libraries)*
- [ ] it should also be possible to simply localize strings used directly into html elements or attributes
- [ ] reading localization data from different `.json` files instead of hardcoding it inside `.js`
- [ ] we need a switch-language menu, and changes should be applied without refreshing the page.
