### ISSUE TITLE
Localized translation falls back to "keys" when switching language before the font has fully loaded

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#1418]
This may be hard to reproduce with Fontra Pak, but with our server deployment, it may take several seconds before the page is loaded, and if you switch the language while loading (the spinner is spinning) the UI falls back to translation keys.

I can only reproduce in an incognito window, presumably because that prevents the cache from being successful.

<img width="404" alt="image" src="https://github.com/googlefonts/fontra/assets/4246121/398997db-5af1-4e52-b3f2-20a30940e7bf">

**Comment by ollimeier** [comment]
@justvanrossum While working with the translations in the sources panel, I am wondering if the key could be simply default english?
Currently it works like that:
`translate("some.translation.key")` -> "some.tranlation.key" is the key and if the key does not exist in the selected language it falls back to the key "some.tranlation.key" which is not very user friendly.
But what if the key is already nicely formatted english, like:
`translate("Some translation key")` -> in that case we don't need to specify any default language, because it will use the key as default which is already formatted well.
Or does this has any disadvantages I don't see or is this not best practice I am not aware of?

By the way, there are some duplicates in the json file, like:
  "axes.mapping.values.name": "Name",
  "axes.names.name": "Name",

If we would use only the key "Name" we would avoid such duplicates as well.

**Comment by justvanrossum** [comment]
One disadvantage is that if we tweak an English string, it would affect all translation files.

The prefixes nicely organize translations by topic, and can be sorted.

I think there is a timing issue: the translation code can be triggered before the language file has been loaded.
