### ISSUE TITLE
Bug - Double clicking on component

### ISSUE THREAD

**Issue by GaetanBaehr** [googlefonts/fontra#1601]
It's currently impossible to open a component by double clicking on it, the pop up disappears instantly

**Comment by ollimeier** [comment]
@GaetanBaehr  I sadly cannot reproduce the issue:


https://github.com/user-attachments/assets/7b0cf69e-f456-4ad9-8627-7b04cffefd6a


Is it possible to get some more insides or even the file you have the issues with? Is there any console log error you can share? Does it happen with all components or just with some specific? 

Thanks a lot in advance.

**Comment by justvanrossum** [comment]
Try this:
- put a glyph with components in edit mode
- double click a component
- the dialog show normally
- don't click a dialog button, but click _outside_ the dialog to dismiss it
- then double click the component again, but make sure it is not where the dialog will be
- observe the diolog pop up briefly but directly disappearing

I suspect the bug is with the dialog code, that perhaps some flag or value doesn't get reset.
