### ISSUE TITLE
Hovering over an icon can trigger the scroll bar

### ISSUE THREAD

**Issue by navv-1** [googlefonts/fontra#1759]
I think this is not intended
![Image](https://github.com/user-attachments/assets/d37021a3-9758-4d67-882f-4385933df08e)

**Comment by ollimeier** [comment]
Thanks a lot for the feedback. 
Can you please provide some information about the used browser and operating system. 
Thanks in advance.

**Comment by navv-1** [comment]
I use chrome on windows 10

**Comment by justvanrossum** [comment]
This is somewhat related to https://github.com/googlefonts/fontra/issues/1388.

@hwoongkang, in case you have a moment, since you so expertly fixed that issue, do you happen to have an idea how we should approach fixing this?

Our icons grow a little on hover, but this should obviously not affect the layout around it.

**Comment by hwoongkang** [comment]
I will try to look into it. I am struggling to reproduce the error in MacOS, but I will try my best :)

**Comment by hwoongkang** [comment]
So the DOM tree of the reported problem is somewhat like this:
```
<panel-selection-info>
  <ui-form>
    <div class="ui-form-header">
      "text"
      <ui-button />
    </div>
    ...
  </ui-form>
</panel-selection-info>
```

right now, `panel-selection-info` has `padding: 1em` and `ui-form` has `padding: 0`

but since 
1. ui-button for the header is placed in the right-most position
2. and it grows in size as the user hovers,

the overall width of `ui-form` grows and overflow occurs for the `panel-selection-info`.

Thus there are several solutions to tackle this, but we have to compromise in some way, since `ui-form` is quite frequently used.

1. add small padding (e.g. `0.2 em`) to `ui-form`.
2. add small right-side padding to `ui-form.header`
3. specifically add small padding, to `panel-selection-info > ui-form`.

As far as I understood the codebase, `panel-selection-info` is somewhat "singular" component that is only used once, so I guess third option might be the best, the only downside being very specific(and ugly) patch.

**Comment by hwoongkang** [comment]
Oh I noticed the second overflow after writing the comment. In that case maybe 
4. adding some margin to `ui-button` 

could be also a solution.

**Comment by hwoongkang** [comment]
The problem occurs since `ui-form` overflows the parent div (in this case `panel-selection-info` or `panel-transformation`).

When 
1. some `ui-button`s are place in the 'extreme' (either right-most or bottom-most) position,
2. and it grows in size as user hovers on it,

the size of the `ui-form` itself grows, resulting in an overflow, which makes the scrollbar to appear.

The simplest solution I could make was to add small padding to the `ui-form`: (e.g. `padding; 0.2em`)

but this does change the overall appearance of the app.

Or maybe we could add auxiliary padding to the reported cases: add padding-right to `panel-selection-info > ui-form > header` and add padding-bottom to `panel-transformation  > ui-form > universal row`

**Comment by justvanrossum** [comment]
Thank you so much for the analysis.

I would prefer a solution within the `icon-button` web component: while the icon should scale on hover, the containing box should be static. Perhaps we need a div around the button element to keep the button in check. Or make sure we do the transform on the icon alone, and not the button.
