### ISSUE TITLE
Lock button tooltip

### ISSUE THREAD

**Issue by navv-1** [googlefonts/fontra#1768]
I just noticed the lock button tooltip is slightly clipped at the top.

![Image](https://github.com/user-attachments/assets/36228a05-8e53-4e8e-8488-5c0d7095f7aa)

**Comment by giovanniTramonto** [comment]
When removing `overflow-x` + `overflow-y` from `ui-form` and `overflow-y` from `div.ui-form` clipping is gone. 
Overflow could be set in `.selection-info` instead, but would require some general layout adjustments.
Actually, https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_anchor_positioning would be great, because anchor can be placed inside `overflow: hidden`, but the module was only releases this year in Chrome and Edge.

**Comment by justvanrossum** [comment]
Fixed by https://github.com/googlefonts/fontra/pull/1861

**Comment by justvanrossum** [comment]
While I like the concept of anchor positioning, I don't like to depend on a (huge!) polyfill. Maybe we should come back to this once anchor positioning is supported everywhere.
