### ISSUE TITLE
set default source name 

### ISSUE THREAD

**Issue by GaetanBaehr** [googlefonts/fontra#427]
When creating a new source would be nice to have a default source name based on the location of this source

as RoboCJK does here https://github.com/BlackFoundryCom/robo-cjk/blob/b99f24a2cb082954706d2b58ea5862b116dd5bac/sources/views/accordionViews.py#L1037

**Comment by justvanrossum** [comment]
Would it be an idea to omit the axes that are set to the default position?

**Comment by justvanrossum** [comment]
The RoboCJK format is this:

    wdth100_wght700

Since we often uses axes with a 0..1 range, I think it's valuable to keep one digit of precision (if it's there). So we'd get names like:

    wdth0.8_wght0.3

The dot makes it less legible, though.

In other parts of Fontra, I use this format:

    wdth=0.8,wght=0.3

I think this reads much nicer, with and without decimal:

    wdth=100,wght=700

I would prefer this format.

@GaetanBaehr, what do you say?

**Comment by justvanrossum** [comment]
I merged the PR using my suggested format, but we can gladly discuss and change further.
