### ISSUE TITLE
Smooth tangent points won't move left or right in a group of selection

### ISSUE THREAD

**Issue by mrk-z** [googlefonts/fontra#512]
When I select a group of points that include tangent points (going from straight to curve), and try to move everything left and right, these tangent points would only move up and down (both on and off curve points).

for example these;
<img width="901" alt="Capture d’écran 2023-06-07 à 15 51 27" src="https://github.com/googlefonts/fontra/assets/56224289/49cef0b1-e403-48ad-8cbd-8a96d11803dc">

https://github.com/googlefonts/fontra/assets/4246121/29d02ccb-0b4e-4149-94b3-b82d293e53bf

If I move everything up and down, they work fine.
If I convert the tangent points into corner points, they also work fine in either directions.

**Comment by justvanrossum** [comment]
So, this currently "behaves as intended", but perhaps we should change the intention.

**Comment by adrientetar** [comment]
I don't know what the algorithm to move points looks like, but I can share how I have it: as a two pass algorithm, the first pass is move selected points and off curves connected to a selected on curve - the second pass is to apply point constraints.
I round to the grid is both of these passes, which probably isn't how it should work (probably there should be a single rounding pass at the end?) but so far what I have works well enough.

**Comment by justvanrossum** [comment]
> I don't know what the algorithm to move points looks like

Fontra also uses a two-pass algorithm.

The problem in this issue is not about "how to implement behavior X", but rather to figure our what is the behavior that we really want. 

Fontra currently has strict constraints on off-curve points _that are selected_. If an off-curve point is not selected, the constrain algorithm can do whatever it wants. But if a tangent point (line-curve transition) is selected _as well as_ the assiciated off-curve point, the only reasonable behavior (according to Fontra current opinion) is to constrain both the tangent and the off-curve point along the original tangent line.

To make Fontra's behavior more intuitive, either it should not select the handles, _or_ it should let go of the additional constraint of the selected off-curve.

I'm tempted to go with the former (not select the handles, which relates to #511), but it has some deeper consequences that I need to get sorted out.

**Comment by justvanrossum** [comment]
To illustrate Fontra's tangent behavior with the off-curve not selected, and selected, respectively:

https://github.com/googlefonts/fontra/assets/4246121/99e61e02-ab31-4605-ae9d-f22089d462b7


https://github.com/googlefonts/fontra/assets/4246121/995bd233-7526-4fb7-9564-5afb221a5e7f

**Comment by adrientetar** [comment]
I see. I think if both these points are selected, they should both move, they don't need to be forced in the same axis but after moving you can constrain the off curve to align to the 2 previous on curves axis.
