### ISSUE TITLE
[ruler] Ruler should take the sidebearings into account

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#616]
Maybe also the CJK design frame?

**Comment by mrk-z** [comment]
I don't think measuring the CJK design frame is necessary, just measuring the sidebearing is enough. The distance between the CJK frame and the sidebearing is always constant, and it might get too busy towards the edges with a lot of things to measure.

(Instead of measuring the CJK design frame, it'd be useful to have a different tool to show whether a point/component is on/aligned with the design frame, like for Latin there are tools to show whether points are on baseline/x-height/etc.)
